[tool.poetry]
name = "it-prog"
version = "0.1.0"
description = ""
authors = ["oneegin <onegin3012@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
